// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeQdfJ9ut80DovUKm4_UN0Tyr5_YxG_og',
    appId: '1:763868360994:web:b5143529e6b774c6abb57b',
    messagingSenderId: '763868360994',
    projectId: 'nao-f-89a7e',
    authDomain: 'nao-f-89a7e.firebaseapp.com',
    storageBucket: 'nao-f-89a7e.appspot.com',
    measurementId: 'G-PK5Y69QDVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu5fCFRT98xr5hPUo07EUzN64ToBIPl6A',
    appId: '1:763868360994:android:77651ecbd6eeb4a9abb57b',
    messagingSenderId: '763868360994',
    projectId: 'nao-f-89a7e',
    storageBucket: 'nao-f-89a7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoK4R0CFg1gCLvm8o5KBgOeAwDyo91Wvc',
    appId: '1:763868360994:ios:abf104fc37d4c8b3abb57b',
    messagingSenderId: '763868360994',
    projectId: 'nao-f-89a7e',
    storageBucket: 'nao-f-89a7e.appspot.com',
    iosClientId: '763868360994-sur4eml13483h1n1af2nbiictpca3eip.apps.googleusercontent.com',
    iosBundleId: 'com.example.naoflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoK4R0CFg1gCLvm8o5KBgOeAwDyo91Wvc',
    appId: '1:763868360994:ios:abf104fc37d4c8b3abb57b',
    messagingSenderId: '763868360994',
    projectId: 'nao-f-89a7e',
    storageBucket: 'nao-f-89a7e.appspot.com',
    iosClientId: '763868360994-sur4eml13483h1n1af2nbiictpca3eip.apps.googleusercontent.com',
    iosBundleId: 'com.example.naoflutter',
  );
}
